# Generated by Django 5.1.7 on 2025-03-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="upvotes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="upvotes",
            field=models.IntegerField(default=0),
        ),
    ]
